[theme]
name = "CrayonCraze"

[prompt.colors]
0 = "#ff0000"
1 = "#00ff00"
2 = "#0000ff"
3 = "#ffff00"
4 = "#ff00ff"
5 = "#00ffff"
6 = "#ff8000"
7 = "#00ff80"
8 = "#8000ff"
9 = "#ff0080"
start = "#ffff00"
end = "#ff00ff"
git = "#00ffff"
thread = "#ff8000"
time = "#00ff80"
frame = "#8000ff"
host = "#ff0080"
progress = "#ffff00"

[shorten.colors]
templates = "#ff00ff"

[bt.colors]
namespace = "#00ffff"
address = "#ff0000"
function = "#00ff00"
selected-frame-marker = "#ffff00"
filename = "#ff00ff"
object-file = "#00ffff"
default-object = "#ff8000"
rtti-warning = "#ff0080"
argument = "#00ff80"
argvalue = "#ff0000"
numvalue = "#00ffff"
optimized-out = "#ff8000"

[memory.colors]
nullpage = "#ff00ff"
unknown = ",,underline"
ascii = "#00ff00"
stack-own = "#ff0000"
stack-foreign = "#00ffff"
heap = "#ff8000"
mmap = "#ff0080"
shared = "#00ff80"
code = "#ffff00"
bss = "#ff00ff"
readonly = "#00ffff"
writeonly = "#ff0000"
readwrite = "#00ff00"
executable = "#ff8000"
inaccessible = "#ff0080"
invalid = "#00ff80"
section-_interp = "#ff0000"
section-_note_ABI-tag = "#00ffff"
section-_hash = "#ff00ff"
section-_gnu_hash = "#ff8000"
section-_dynsym = "#ff0080"
section-_dynstr = "#00ff00"
section-_gnu_version = "#00ff80"
section-_gnu_version_r = "#ff0000"
section-_rela_dyn = "#00ffff"
section-_rela_plt = "#ff00ff"
section-_init = "#ff8000"
section-_plt = "#ff0080"
section-_text = "#00ff00"
section-_fini = "#00ff80"
section-_rodata = "#ff0000"
section-_stapsdt_base = "#00ffff"
section-_eh_frame_hdr = "#ff00ff"
section-_eh_frame = "#ff8000"
section-_gcc_except_table = "#ff0080"
section-_tdata = "#00ff00"
section-_tbss = "#00ff80"
section-_init_array = "#ff0000"
section-_fini_array = "#00ffff"
section-_data_rel_ro = "#ff00ff"
section-_dynamic = "#ff8000"
section-_got = "#ff0080"
section-_got_plt = "#00ff00"
section-_data = "#00ff80"
section-_bss = "#ff0000"
section-_comment = "#00ffff"
section-_GCC_command_line = "#ff00ff"
section-_note_stapsdt = "#ff8000"
section-_debug_aranges = "#ff0080"
section-_debug_info = "#00ff00"
section-_debug_abbrev = "#00ff80"
section-_debug_line = "#ff0000"
section-_debug_str = "#00ffff"
section-_debug_loc = "#ff00ff"
section-_debug_ranges = "#ff8000"
section-_debug_macro = "#ff0080"

[vmmap.colors]
executable = "#ff00ff"
readonly = "#00ffff"

[asm.colors]
class-jump = "#ff0000"
class-mem = "#00ff00"
class-nop = "#0000ff"
class-bit = "#ffff00"
class-math = "#ff00ff"
class-sys = "#00ffff"
class-ret = "#ff8000"
class-call = "#ff0080"
class-stack = "#00ff80"
class-cond = "#ff0000"
class-vector = "#00ffff"
class-default = "#ff00ff"
namespace = "#00ff00"
function = "#0000ff"
next-marker = "#ffff00"
next2-marker = "#ff00ff"
marker = "#00ffff"
breakpoint-marker = "#ff8000"
breakpoint-disabled-marker = "#ff0080"
addr = "#00ff80"
offset = "#ff0000"
bytes = "#0000ff"
prefix = "#00ff00"

args = "#ff00ff"
variable = "#00ffff"
location = "#ff8000"
explanation = "#00ff80"
unhandled = "#ff0000"
namespace-dot = "#00ff00"
function-dot = "#0000ff"
bytes-dot = "#ffff00"
next-marker-dot = "#ff00ff"
addr-dot = "#00ffff"
offset-dot = "#ff8000"
prefix-dot = "#00ff00"

args-dot = "#ff00ff"
jump-false-dot = "#00ffff"
jump-true-dot = "#ff8000"
jump-dot = "#ff0000"
call-dot = "#00ff80"
jumps = "#ff0000;#00ff00;#0000ff;#ffff00;#ff00ff;#00ffff;#ff8000;#ff0080;#00ff80;#ff0000;#00ff00;#0000ff"

[register.colors]
names = "#ff00ff"
flags = "#00ffff"

[hexdump.colors]
header = "#ff0000"
symbols = "#00ff00;#0000ff;#ffff00;#ff00ff;#00ffff;#ff8000;#ff0080;#00ff80;#ff0000;#00ff00;#0000ff;#ffff00"

[pahole.colors]
members = "#ff0000;#00ff00;#0000ff;#ffff00;#ff00ff;#00ffff;#ff8000;#ff0080;#00ff80;#ff0000;#00ff00;#0000ff"

[ftree.colors]
invalid = "#ff00ff"
union = "#00ffff"
virtual-cast = "#ff8000"
down-cast = "#ff0080"
blacklist-pointer = "#00ff80"
blacklist-member = "#ff0000"
limited = "#00ff00"
pretty-print = "#0000ff"
variable-name = "#ffff00"
arrows = "#ff0000;#00ff00;#0000ff;#ffff00;#ff00ff;#00ffff;#ff8000;#ff0080;#00ff80;#ff0000;#00ff00;#0000ff"

[unwind.colors]
hint = "#00ffff"
hint-start = "#ff00ff"

[history.colors]
marker = "#ff0000"
background = "#000000"
statistics = "#00ff00"
prompt = "#0000ff"
match = "#ffff00"

[va.colors]
fixed-float = "#ff00ff"
vararg-float = "#00ffff"
fixed-int = "#ff8000"
vararg-int = "#ff0080"

[rtos.colors]
active-task = "#00ff00"
marked-task = "#ff0000"

[list.colors]
marker = "#ffff00"

[swo.colors]
0 = "#ff0000"
1 = "#00ff00"
2 = "#0000ff"
3 = "#ffff00"
4 = "#ff00ff"
5 = "#00ffff"
6 = "#ff8000"
7 = "#ff0080"
8 = "#00ff80"
9 = "#ff0000"
