[theme]
name = "Grayscale"

[prompt.colors]
0 = "#ccc"
1 = "#bbb"
2 = "#aaa"
3 = "#999"
4 = "#888"
5 = "#777"
6 = "#666"
7 = "#555"
8 = "#444"
9 = "#333"
start = "#eee"
end = "#ddd"
git = "#ccc"
thread = "#bbb"
time = "#aaa"
frame = "#999"
host = "#888"
progress = "#777"

[shorten.colors]
templates = "#888"

[bt.colors]
namespace = "#ccc"
address = "#aaa"
function = "#bbb"
selected-frame-marker = "#eee"
filename = "#999"
object-file = "#888"
default-object = "#777"
rtti-warning = "#666"
argument = "#555"
argvalue = "#444"
numvalue = "#ccc"
optimized-out = "#aaa"

[memory.colors]
nullpage = "#ccc"
unknown = ",,underline"
ascii = "#bbb"
stack-own = "#aaa"
stack-foreign = "#999"
heap = "#888"
mmap = "#777"
shared = "#666"
code = "#555"
bss = "#444"
readonly = "#333"
writeonly = "#222"
readwrite = "#111"
executable = "#000"
inaccessible = "#fff"
invalid = "#ccc"
section-_interp = "#aaa"
section-_note_ABI-tag = "#999"
section-_hash = "#888"
section-_gnu_hash = "#777"
section-_dynsym = "#666"
section-_dynstr = "#555"
section-_gnu_version = "#444"
section-_gnu_version_r = "#333"
section-_rela_dyn = "#222"
section-_rela_plt = "#111"
section-_init = "#000"
section-_plt = "#ccc"
section-_text = "#bbb"
section-_fini = "#aaa"
section-_rodata = "#999"
section-_stapsdt_base = "#888"
section-_eh_frame_hdr = "#777"
section-_eh_frame = "#666"
section-_gcc_except_table = "#555"
section-_tdata = "#444"
section-_tbss = "#333"
section-_init_array = "#222"
section-_fini_array = "#111"
section-_data_rel_ro = "#000"
section-_dynamic = "#ccc"
section-_got = "#bbb"
section-_got_plt = "#aaa"
section-_data = "#999"
section-_bss = "#888"
section-_comment = "#777"
section-_GCC_command_line = "#666"
section-_note_stapsdt = "#555"
section-_debug_aranges = "#444"
section-_debug_info = "#333"
section-_debug_abbrev = "#222"
section-_debug_line = "#111"
section-_debug_str = "#000"
section-_debug_loc = "#ccc"
section-_debug_ranges = "#bbb"
section-_debug_macro = "#aaa"

[vmmap.colors]
executable = "#ccc"
readonly = "#bbb"

[asm.colors]
class-jump = "#aaa"
class-mem = "#999"
class-nop = "#888"
class-bit = "#777"
class-math = "#666"
class-sys = "#555"
class-ret = "#444"
class-call = "#333"
class-stack = "#222"
class-cond = "#111"
class-vector = "#000"
class-default = "#ccc"
namespace = "#bbb"
function = "#aaa"
next-marker = "#999"
next2-marker = "#888"
marker = "#777"
breakpoint-marker = "#666"
breakpoint-disabled-marker = "#555"
addr = "#444"
offset = "#333"
bytes = "#222"
prefix = "#111"

args = "#ccc"
variable = "#bbb"
location = "#aaa"
explanation = "#bbb"
unhandled = "#aaa"
namespace-dot = "#ccc"
function-dot = "#bbb"
bytes-dot = "#aaa"
next-marker-dot = "#999"
addr-dot = "#888"
offset-dot = "#777"
prefix-dot = "#666"

args-dot = "#444"
jump-false-dot = "#333"
jump-true-dot = "#222"
jump-dot = "#111"
call-dot = "#000"
jumps = "#ccc;#bbb;#aaa;#999;#888;#777"

[register.colors]
names = "#ccc"
flags = "#bbb"

[hexdump.colors]
header = "#aaa"
symbols = "#ccc;#bbb;#aaa;#999;#888;#777"
unknown-bytes = "#666"

[pahole.colors]
members = "#ccc;#bbb;#aaa;#999;#888;#777"

[ftree.colors]
invalid = "#ccc"
union = "#bbb"
virtual-cast = "#aaa"
down-cast = "#999"
blacklist-pointer = "#888"
blacklist-member = "#777"
limited = "#666"
pretty-print = "#555"
variable-name = "#444"
arrows = "#ccc;#bbb;#aaa;#999;#888;#777"

[unwind.colors]
hint = "#ccc"
hint-start = "#bbb"

[history.colors]
marker = "#aaa"
background = "#000"
statistics = "#ccc"
prompt = "#bbb"
match = "#aaa"

[va.colors]
fixed-float = "#ccc"
vararg-float = "#bbb"
fixed-int = "#aaa"
vararg-int = "#999"

[rtos.colors]
active-task = "#ccc"
marked-task = "#bbb"

[list.colors]
marker = "#aaa"

[swo.colors]
0 = "#ccc"
1 = "#bbb"
2 = "#aaa"
3 = "#999"
4 = "#888"
5 = "#777"
6 = "#666"
7 = "#555"
8 = "#444"
9 = "#333"
