[theme]
name = "MatrixGreen"

[prompt.colors]
0 = "#00ff00"
1 = "#00cc00"
2 = "#009900"
3 = "#006600"
4 = "#003300"
5 = "#00ff33"
6 = "#00cc33"
7 = "#009933"
8 = "#006633"
9 = "#003333"
start = "#00ff00"
end = "#00cc00"
git = "#009900"
thread = "#006600"
time = "#003300"
frame = "#00ff33"
host = "#00cc33"
progress = "#009933"

[shorten.colors]
templates = "#00ff00"

[bt.colors]
namespace = "#00ff00"
address = "#00cc00"
function = "#00ff00"
selected-frame-marker = "#00ff33"
filename = "#00cc00"
object-file = "#009900"
default-object = "#006600"
rtti-warning = "#00ff00"
argument = "#00cc00"
argvalue = "#009900"
numvalue = "#00ff33"
optimized-out = "#00cc33"

[memory.colors]
nullpage = "#00ff00"
unknown = ",,underline"
ascii = "#00ff00"
stack-own = "#00cc00"
stack-foreign = "#009900"
heap = "#006600"
mmap = "#003300"
shared = "#00ff33"
code = "#00cc33"
bss = "#009933"
readonly = "#006633"
writeonly = "#003333"
readwrite = "#00ff00"
executable = "#00cc00"
inaccessible = "#009900"
invalid = "#006600"
section-_interp = "#003300"
section-_note_ABI-tag = "#00ff33"
section-_hash = "#00cc33"
section-_gnu_hash = "#009933"
section-_dynsym = "#006633"
section-_dynstr = "#003333"
section-_gnu_version = "#00ff00"
section-_gnu_version_r = "#00cc00"
section-_rela_dyn = "#009900"
section-_rela_plt = "#006600"
section-_init = "#003300"
section-_plt = "#00ff33"
section-_text = "#00cc33"
section-_fini = "#009933"
section-_rodata = "#006633"
section-_stapsdt_base = "#003333"
section-_eh_frame_hdr = "#00ff00"
section-_eh_frame = "#00cc00"
section-_gcc_except_table = "#009900"
section-_tdata = "#006600"
section-_tbss = "#003300"
section-_init_array = "#00ff33"
section-_fini_array = "#00cc33"
section-_data_rel_ro = "#009933"
section-_dynamic = "#006633"
section-_got = "#003333"
section-_got_plt = "#00ff00"
section-_data = "#00cc00"
section-_bss = "#009900"
section-_comment = "#006600"
section-_GCC_command_line = "#003300"
section-_note_stapsdt = "#00ff33"
section-_debug_aranges = "#00cc33"
section-_debug_info = "#009933"
section-_debug_abbrev = "#006633"
section-_debug_line = "#003333"
section-_debug_str = "#00ff00"
section-_debug_loc = "#00cc00"
section-_debug_ranges = "#009900"
section-_debug_macro = "#006600"

[vmmap.colors]
executable = "#00ff00"
readonly = "#00cc00"

[asm.colors]
class-jump = "#00ff00"
class-mem = "#00cc00"
class-nop = "#009900"
class-bit = "#006600"
class-math = "#003300"
class-sys = "#00ff33"
class-ret = "#00cc33"
class-call = "#009933"
class-stack = "#006633"
class-cond = "#003333"
class-vector = "#00ff00"
class-default = "#00cc00"
namespace = "#009900"
function = "#006600"
next-marker = "#003300"
next2-marker = "#00ff33"
marker = "#00cc33"
breakpoint-marker = "#009933"
breakpoint-disabled-marker = "#006633"
addr = "#003333"
offset = "#00ff00"
bytes = "#00cc00"
prefix = "#009900"

args = "#003300"
variable = "#00ff33"
location = "#00cc33"
explanation = "#ccffcc"
unhandled = "#009900"
namespace-dot = "#00ff00"
function-dot = "#00cc00"
bytes-dot = "#009900"
next-marker-dot = "#006600"
addr-dot = "#003300"
offset-dot = "#00ff33"
prefix-dot = "#00cc33"

args-dot = "#006633"
jump-false-dot = "#003333"
jump-true-dot = "#00ff00"
jump-dot = "#00cc00"
call-dot = "#009900"
jumps = "#00ff00;#00cc00;#009900;#006600;#003300;#00ff33;#00cc33;#009933;#006633;#003333;#00ff00;#00cc00"

[register.colors]
names = "#00ff00"
flags = "#00cc00"

[hexdump.colors]
header = "#00ff00"
symbols = "#00ff00;#00cc00;#009900;#006600;#003300;#00ff33;#00cc33;#009933;#006633;#003333;#00ff00;#00cc00"
unknown-bytes = "#00ff00"

[pahole.colors]
members = "#00ff00;#00cc00;#009900;#006600;#003300;#00ff33;#00cc33;#009933;#006633;#003333;#00ff00;#00cc00"

[ftree.colors]
invalid = "#00ff00"
union = "#00cc00"
virtual-cast = "#009900"
down-cast = "#006600"
blacklist-pointer = "#003300"
blacklist-member = "#00ff33"
limited = "#00cc33"
pretty-print = "#009933"
variable-name = "#006633"
arrows = "#00ff00;#00cc00;#009900;#006600;#003300;#00ff33;#00cc33;#009933;#006633;#003333;#00ff00;#00cc00"

[unwind.colors]
hint = "#00ff00"
hint-start = "#00cc00"

[history.colors]
marker = "#00ff00"
background = "#000000"
statistics = "#00cc00"
prompt = "#009900"
match = "#006600"

[va.colors]
fixed-float = "#00ff00"
vararg-float = "#00cc00"
fixed-int = "#009900"
vararg-int = "#006600"

[rtos.colors]
active-task = "#003300"
marked-task = "#00ff33"

[list.colors]
marker = "#00cc33"

[swo.colors]
0 = "#00ff00"
1 = "#00cc00"
2 = "#009900"
3 = "#006600"
4 = "#003300"
5 = "#00ff33"
6 = "#00cc33"
7 = "#009933"
8 = "#006633"
9 = "#003333"
