[theme]
name = "Obsidian"

[prompt.colors]
0 = "#d0d0d0"
1 = "#d0d0d0"
2 = "#d0d0d0"
3 = "#d0d0d0"
4 = "#d0d0d0"
5 = "#d0d0d0"
6 = "#d0d0d0"
7 = "#d0d0d0"
8 = "#d0d0d0"
9 = "#d0d0d0"
start = "#d0d0d0"
end = "#ffffff"
git = "#90ee90"
thread = "#99ccff"
time = "#ffffff"
frame = "#99ccff"
host = "#ffd700"
progress = "#ffcc00"
[shorten.colors]
templates = "#ff8c00"
[bt.colors]
namespace = "#88ccff"
address = "#cccccc"
function = "#9999ff"
selected-frame-marker = "#00ff00"
filename = "#d0d0d0"
object-file = "#ff9999"
default-object = "#ff99ff"
rtti-warning = "#ff4500"
argument = "#008080"
argvalue = "#808080"
numvalue = "#ff8c00"
optimized-out = "#555555"
[memory.colors]
nullpage = "#ff4500"
unknown = ",,underline"
ascii = "#ffff00"
stack-own = "#00ff00"
stack-foreign = "#ff8c00"
heap = "#00bfff"
mmap = "#0000ff"
shared = "#00bfff"
code = "#800080"
bss = "#00ffff"
readonly = "#00bfff"
writeonly = "#ff8c00"
readwrite = "#00ff00"
executable = "#800080"
inaccessible = "#ff4500"
invalid = "#00bfff"
section-_interp = "#888888"
section-_note_ABI-tag = "#888888"
section-_hash = "#888888"
section-_gnu_hash = "#888888"
section-_dynsym = "#888888"
section-_dynstr = "#888888"
section-_gnu_version = "#888888"
section-_gnu_version_r = "#888888"
section-_rela_dyn = "#888888"
section-_rela_plt = "#888888"
section-_init = "#888888"
section-_plt = "#888888"
section-_text = "#00bfff"
section-_fini = "#888888"
section-_rodata = "#00bfff"
section-_stapsdt_base = "#888888"
section-_eh_frame_hdr = "#888888"
section-_eh_frame = "#888888"
section-_gcc_except_table = "#888888"
section-_tdata = "#888888"
section-_tbss = "#888888"
section-_init_array = "#888888"
section-_fini_array = "#888888"
section-_data_rel_ro = "#888888"
section-_dynamic = "#888888"
section-_got = "#888888"
section-_got_plt = "#888888"
section-_data = "#888888"
section-_bss = "#888888"
section-_comment = "#888888"
section-_GCC_command_line = "#888888"
section-_note_stapsdt = "#888888"
section-_debug_aranges = "#888888"
section-_debug_info = "#888888"
section-_debug_abbrev = "#888888"
section-_debug_line = "#888888"
section-_debug_str = "#888888"
section-_debug_loc = "#888888"
section-_debug_ranges = "#888888"
section-_debug_macro = "#888888"
[vmmap.colors]
executable = "#00bfff"
readonly = "#00bfff"
[asm.colors]
class-jump = "#ff4500"
class-mem = "#00ffff"
class-nop = "#808080"
class-bit = "#ff8c00"
class-math = "#00bfff"
class-sys = "#ff69b4"
class-ret = "#00ff00"
class-call = "#6666ff"
class-stack = "#00ff00"
class-cond = "#ff4500"
class-vector = "#00ffff"
class-default = "#ff8c00"
namespace = "#88ccff"
function = "#9999ff"
next-marker = "#00ff00"
next2-marker = "#008000"
marker = "#0000ff"
breakpoint-marker = "#ff4500"
breakpoint-disabled-marker = "#ff4500"
addr = "#cccccc"
offset = "#888888"
bytes = "#0000ff"
prefix = "#888888"
args = "#9999ff"
variable = "#ff8c00"
location = "#0000ff"
explanation = "#6666ff"
unhandled = "#ff4500"
namespace-dot = "#0000ff"
function-dot = "#0000ff"
bytes-dot = "#0000ff"
next-marker-dot = "#00ff00"
addr-dot = "#0000ff"
offset-dot = "#888888"
prefix-dot = "#888888"
args-dot = "#0000ff"
jump-false-dot = "#ff4500"
jump-true-dot = "#00ff00"
jump-dot = "#0000ff"
call-dot = "#6666ff"
jumps = "#ff4500;#00ff00;#0000ff;#ff8c00;#ff4500;#00ff00;#0000ff;#ff8c00;#ff4500;#00ff00;#0000ff;#ff8c00"
[register.colors]
names = "#00ffff"
flags = "#ffcc00"
[hexdump.colors]
header = "#ffff00"
symbols = "#ff4500;#00ff00;#0000ff;#ffff00;#ff4500;#00ff00;#0000ff;#ffff00;#ff4500;#00ff00;#0000ff;#ffff00"
unknown-bytes = "#888888"
[pahole.colors]
members = "#ff4500;#00ff00;#0000ff;#ffff00;#ff4500;#00ff00;#0000ff;#ffff00;#ff4500;#00ff00;#0000ff;#ffff00"
[ftree.colors]
invalid = "#ff4500"
union = "#ffff66"
virtual-cast = "#ccaaee"
down-cast = "#aaffaa"
blacklist-pointer = "#ff9900"
blacklist-member = "#334400"
limited = "#88aaff"
pretty-print = "#76d7c4"
variable-name = "#ffffff"
arrows = "#ff0000;#00ff00;#0000ff;#ff8000;#ff00ff;#00ffff;#ff0000;#00ff00;#0000ff;#ff8000;#ff00ff;#00ffff"
[unwind.colors]
hint = "#ff8c00"
hint-start = "#ffcc00"
[history.colors]
marker = "#d1005c"
background = "#000000"
statistics = "#a0a0a0"
prompt = "#00ffff"
match = "#00ff00"
[va.colors]
fixed-float = "#838"
vararg-float = "#608"
fixed-int = "#953"
vararg-int = "#c43"
[rtos.colors]
active-task = "#00ff00"
marked-task = "#0000ff"
[list.colors]
marker = "#00ff00"
[swo.colors]
0 = "#ffffff"
1 = "#ffff77"
2 = "#ff9900"
3 = "#ff7777"
4 = "#00ff00"
5 = "#0000ff"
6 = "#ff00ff"
7 = "#00ffff"
8 = "#88aaff"
9 = "#aa00aa"
