[theme]
name = "basic"

[prompt.colors]
0 = "#ffffff"
1 = "#ffffff"
2 = "#ffffff"
3 = "#ffffff"
4 = "#ffffff"
5 = "#ffffff"
6 = "#ffffff"
7 = "#ffffff"
8 = "#ffffff"
9 = "#ffffff"
start = "#ffffff"
end = "#ffffff"
git = "#ffffff"
thread = "#ffffff"
time = "#ffffff"
frame = "#ffffff"
host = "#ffffff"
progress = "#ffffff"

[shorten.colors]
templates = "#fff"

[bt.colors]
namespace = "#fff"
address = ""
function = "#fff"
selected-frame-marker = "#fff"
filename = "#ffffff"
object-file = "#ffffff"
default-object = "#ffffff"
rtti-warning = "#fff"
argument = "#ffffff"
argvalue = ""
numvalue = "#fff"
optimized-out = "#fff"

[memory.colors]
nullpage = "#fff"
unknown = ",,underline"
ascii = "#fff"
stack-own = "#fff"
stack-foreign = "#fff"
heap = "#fff"
mmap = "#fff"
shared = "#fff"
code = "#fff"
bss = "#fff"
readonly = "#fff"
writeonly = "#fff"
readwrite = ""
executable = "#fff"
inaccessible = "#fff"
invalid = "#fff"
section-_interp = ""
section-_note_ABI-tag = ""
section-_hash = ""
section-_gnu_hash = ""
section-_dynsym = ""
section-_dynstr = ""
section-_gnu_version = ""
section-_gnu_version_r = ""
section-_rela_dyn = ""
section-_rela_plt = ""
section-_init = ""
section-_plt = ""
section-_text = ""
section-_fini = ""
section-_rodata = ""
section-_stapsdt_base = ""
section-_eh_frame_hdr = ""
section-_eh_frame = ""
section-_gcc_except_table = ""
section-_tdata = ""
section-_tbss = ""
section-_init_array = ""
section-_fini_array = ""
section-_data_rel_ro = ""
section-_dynamic = ""
section-_got = ""
section-_got_plt = ""
section-_data = ""
section-_bss = ""
section-_comment = ""
section-_GCC_command_line = ""
section-_note_stapsdt = ""
section-_debug_aranges = ""
section-_debug_info = ""
section-_debug_abbrev = ""
section-_debug_line = ""
section-_debug_str = ""
section-_debug_loc = ""
section-_debug_ranges = ""
section-_debug_macro = ""

[vmmap.colors]
executable = "#fff"
readonly = "#fff"

[asm.colors]
class-jump = "#fff"
class-mem = "#fff"
class-nop = "#fff"
class-bit = "#fff"
class-math = "#fff"
class-sys = "#fff"
class-ret = "#fff"
class-call = "#fff"
class-stack = "#fff"
class-cond = "#fff"
class-vector = "#fff"
class-default = "#fff"
namespace = "#fff"
function = "#fff"
next-marker = "#fff"
next2-marker = "#fff"
marker = "#fff"
breakpoint-marker = "#fff"
breakpoint-disabled-marker = "#fff"
addr = ""
offset = "#fff"
bytes = "#fff"
prefix = ""
args = "#fff"
variable = "#fff"
location = "#fff"
explanation = "#ffffff"
unhandled = "#fff"
namespace-dot = "#ffffff"
function-dot = "#ffffff"
bytes-dot = "#ffffff"
next-marker-dot = "#ffffff"
addr-dot = "#ffffff"
offset-dot = "#ffffff"
prefix-dot = ""
args-dot = "#ffffff"
jump-false-dot = "#ffffff"
jump-true-dot = "#ffffff"
jump-dot = "#ffffff"
call-dot = "#ffffff"
jumps = "#fff;#fff;#fff;#fff;#fff;#fff"

[register.colors]
names = "#fff"
flags = "#ffffff"

[hexdump.colors]
header = "#fff"
symbols = "#fff;#fff;#fff;#fff;#fff;#fff"
unknown-bytes = "#ffffff"

[pahole.colors]
members = "#fff;#fff;#fff;#fff;#fff;#fff"

[ftree.colors]
invalid = "#ffffff"
union = "#ffffff"
virtual-cast = "#ffffff"
down-cast = "#ffffff"
blacklist-pointer = "#ffffff"
blacklist-member = "#ffffff"
limited = "#ffffff"
pretty-print = "#ffffff"
variable-name = ""
arrows = "#ffffff;#ffffff;#ffffff;#ffffff;#ffffff;#ffffff"

[unwind.colors]
hint = "#fff"
hint-start = "#fff"

[history.colors]
marker = "#ffffff"
background = "#ffffff"
statistics = "#ffffff"
prompt = "#ffffff"
match = "#ffffff"

[va.colors]
fixed-float = "#fff"
vararg-float = "#fff"
fixed-int = "#fff"
vararg-int = "#fff"

[rtos.colors]
active-task = "#fff"
marked-task = "#fff"

[list.colors]
marker = "#fff"

[swo.colors]
0 = "#ffffff"
1 = "#ffffff"
2 = "#ffffff"
3 = "#ffffff"
4 = "#ffffff"
5 = "#ffffff"
6 = "#ffffff"
7 = "#ffffff"
8 = "#ffffff"
9 = "#ffffff"

